services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "finance_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
    ports:
      - "5440:5432"
    volumes:
      - pg_vol:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "finance_db" ]
      interval: 5s
      timeout: 5s
      retries: 10

  finance_app:
    build: .
    environment:
      SERVER_PORT: "8000"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_vol:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_vol:
  redis_vol:  # добавить этот объем