services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "finance_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
    ports:
      - "5440:5432"
    volumes:
      - pg_vol:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "finance_db" ]
      interval: 5s
      timeout: 5s
      retries: 10

  finance_app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg_vol: