name: Build and Push services to server

on:
  workflow_dispatch:
    inputs:
      myInput:
        description: 'User Input:'
        required: true
        default: "Run"

jobs:
  job1:
    name: Build and push service
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.DOCKERHUB_LOGIN }}
      DOCKER_NAME: ${{ secrets.DOCKER_NAME }}
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -t test$LOGIN/$DOCKER_NAME:latest .
      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin
      - name: Push image
        run: docker push $LOGIN/$DOCKER_NAME:latest

  job2:
    name: Publish
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Run sshpass commands
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{ secrets.VIRTUAL_IP }}
          user: ${{ secrets.VIRTUAL_LOGIN }}
          key: ${{ secrets.SERVER_KEY }}
          run: |
            cd ~/financeapp
            sudo docker compose pull
            sudo docker compose up -d